### PR TITLE
Resource Management API

### LINKED ISSUE #166: Design and Implement initial resource management interface:
- User specified max concurrency (go-routine limit for queries making progress?)
  - User specified max memory per query
  - User specified query priority.

### PR DESCRIPTION
**Pull request by nathanielc**
This PR introduces a new structure on the QuerySpec that defines the how the query should manage its resources.

The ResourceManagement is designed such that the default zero value represents an query that has the highest priority and unlimited resources.

TODO
- [x] Add flags to iflqd to specify server resource limits.

Fixes #166

Three options are provided as part of the type:

```go
// Priority or the query.
// Queries with a lower value will move to the front of the priority queue.
// A zero value indicates the highest priority.
Priority Priority `json:"priority"`

// ConcurrencyQuota is the number of concurrency workers allowed to process this query.
// A zero value indicates the planner can pick the optimal concurrency.
ConcurrencyQuota int `json:"concurrency_quota"`

// MemoryBytesQuota is the number of bytes of RAM this query may consume.
// There is a small amount of overhead memory being consumed by a query that will not be counted towards this limit.
// A zero value indicates unlimited.
MemoryBytesQuota int64 `json:"memory_bytes_quota"`
```

### CODE REVIEW

**Comment by nathanielc** [comment]
What follows is a simple write up about the ideas behind Resource Management in IFQL.

Requirements

1. Impossible to crash process with bad queries.
2. Fairness system: queries can be restricted to the background having less priority than queries running in the foreground.
3. Place upper bounds on resource consumption of a query. Limits can be placed on RAM, CPU, Disk IO, and Network IO.
4. Queries can be canceled. This can be either because the client requesting the query cancels or because another party requests that it be canceled. 
5. The list of running queries and the resources they are using should be available upon request.


Non-Requirements

The following are good ideas that we should implement, but should be done at a higher level than the IFQL daemon process.

1. Limit total concurrent queries. There are many dimensions along which a user may want to limit query concurrency, (i.e. user/group/tennant etc). These concepts are external to the IFQL daemon. If a query is submitted to IFQL, it will attempt to run it using the available resources according to its priority.
2. Query canceling permissions should be part of an external system. If IFQL receives a request to cancel a query it will do so.

The intent of these non-requirements is so that the IFQL daemons can remain stateless by pushing their state on external systems. This allows for elastic deployment of IFQL daemons.


My general thoughts on implementation are as follows.

Create a ControlPlane type that manages all queries. Queries will have a state (i.e. waiting, planning, executing). The control plane will be able to cancel any running query. 

There will be a priority queue into which new queries are placed. Once a query is at the head of the queue and there is an available worker the query will begin.

To limit RAM usage all allocations for slices of data will go through a common type shared by all operations of the query. As such a request for more RAM will fail the query. 

To limit CPU I don't have a good idea at the moment. It seems like the producer consumer idea might work. Currently each operation of query runs in its own goroutine. I am not sure how to reconcile these well. Seems like if we push all work through a single channel and to let consumers pull off the work, we will create a bottle neck. Worth some investigation. 

Some questions:

Should the priority queue exist before the planning phase or after? Seems like before makes sense as you can control the rate queries are planned. Also any information derived from the planning step will not effect the query resource management. This probably means we need to watch the RAM usage for the planning step too. Thoughts?

Should the default be a high or low priority query?

**Comment by stuartcarnie** [comment]
@nathanielc

I would expect monitoring RAM will be easier as we explore support for Apache Arrow. We'll need some sort of allocator to produce 64-byte aligned, 8-byte padded slices, so we could generalize this for other allocations.

I don't have any good ideas on CPU either. I think "cores" will be too specific a concept, given a CPU is mostly abstracted in Go and we have very little control over scheduling. Attempting to time execution is problematic too, as we can't account for time when the goroutine is suspended due to I/O or to allow other goroutines to run. We could come up with our own accounting for operations and perhaps estimate a CPU cost to run them. PostgreSQL does this for its query optimizer, per [the documentation][0].

That being said, we can limit concurrency and prioritize work (queries) by using a worker pool and a queue.

[0]: https://www.postgresql.org/docs/current/static/runtime-config-query.html

**Comment by nathanielc** [comment]
@stuartcarnie @aanthony1243 This is ready for review. 

At this point, there is control over the concurrency of a query and very rough control over the memory usage of a query.

Concurrency control is implemented using a central dispatcher per query. Each transformation submits work to be done to the dispatcher based on the message queues between them. Then the central dispatcher schedules to work based on the available goroutines.

Memory control is implemented using an Allocator type, all large allocations and frees are reported to this type. Since blocks are immutable and can be consumed by multiple downstream transformations, reference counting is used to know when a block can be freed. In addition the triggering mechanisms are used to know when cached data for a transformation can be freed.

Freeing in this context means that right before we let go of the last reference to the object we inform the Allocator of how much space we were using.

**Comment by nathanielc** [comment]
> Presumably we'll extend the Allocator to produce buffers for Apache Arrow (64-byte aligned / 8-byte padded)

Yes, now we have a starting place.

**Comment by aanthony1243** [comment]
Went through control, query, allocator types.  Looks pretty clean, easy to follow.  Didn't see any major issues.  Really like the allocator design, but we'll have to watch PR's carefully to make sure it's being used exclusively during query execution.  Will the allocator need to be exposed at the query function level (e.g. min/max/sample/limit, etc)?

**Comment by nathanielc** [comment]
>  Will the allocator need to be exposed at the query function level (e.g. min/max/sample/limit, etc)?

Yes, all functions already have access to the allocator, but so far none of them need to directly consume it. They just pass it on to the types they consume.

More specifically all transformations have access to the Allocator. And functions provide a transformation implementation, but most of the time they either consume a prebuilt transformation type like the aggregateTransformation or they consume other types like the block builder that handle the allocations for them.

**Comment by nathanielc** [comment]
> we'll have to watch PR's carefully to make sure it's being used exclusively during query execution. 

I think this will become easier once the Allocator uses Apache Arrow since each block will want to take advantage of the performance it provides.

**Pull request merged**
