### PR TITLE
Cumulative sum

### PR DESCRIPTION
**Pull request by nathanielc**
Add cumulative sum

@jlapacik

TODO:
- [ ] Add support for multiple value columns
- [ ] Add support for multiple data types

### CODE REVIEW

**Comment by jlapacik** [comment]
@nathanielc would you like me to handle the TODOs?

**Comment by nathanielc** [comment]
@jlapacik If you would like to. We always love contributions!

You will not be able to update this PR since I created it as branch. Just fork the repo and submit a new PR and link back to this one.

**Comment by jlapacik** [comment]
Ok will do.

**Comment by nathanielc** [comment]
Closing in favor of #277

**Pull request closed without merging**
