### PR TITLE
First pass at removing {}

### LINKED ISSUE #137: Remove {} around expressions

### PR DESCRIPTION
**Pull request by nathanielc**
Removing the `{}` around expressions is not as easy as expected.

The basic conflict revolves around literals, the parser can't determine the difference between a literal as part of an expression or a literal as part of the top level IFQL language.

I am thinking maybe we just leave them in.

Fixes #137

### CODE REVIEW

**Comment by nathanielc** [comment]
After some discussion we have a new idea for how to represent expressions so they can be clearly understood.

Example:

```javascript
from()
    .filter(f: r => 
        r["_measurement"] == "cpu" 
        and  r["_field"] == "usage_idle" 
        and r["cpu"] == "cpu-total"
    )
```

The above reads as `filter` has a single keyword argument `f` that is the anonymous function that follows. The identifier `r` is the name given to the record for the current invocation of the function. The index `[]` operators extract values from r for use in the conditional statement.

In addition to the above syntax may also be possible to use maps to define several functions as part of a map operation.

Example:
```javascript
var data = from()//....

data.map(f: r => {
    host: r["server"], // rename the server tag to host
    value: r["value"] * r["value"], // square the value of r
})
````

There are two clear benefits over the original design.

* Functions are clearly functions, there is a clear delineation between chaining code and anonymous functions that operate on records.
* Functions have a clear scope, the variable for that scope can be indexed, this removes the ambiguity around the left operand indicating a scope lookup versus the right operand being a literal.

**Comment by pauldix** [comment]
Hmmm, I like the direction. Although for the examples, how do you know when the passed function ends? For the second one you have a single return value, a map. But for the first one it feels like it should be wrapped in parens like:

```javascript
from()
    .filter(f: r => (
        r["_measurement"] == "cpu" 
        and  r["_field"] == "usage_idle" 
        and r["cpu"] == "cpu-total")
    )
```

I like the idea of having the functions be separate. But it makes me wonder if this then gets into introducing function assignments/definitions in addition to the anonymous ones? Also, should the syntax be closer to JS for the "it should look familiar" criteria? So you could do:

```javascript
from()
    .filter(f: function(r) {
        r["_measurement"] == "cpu" 
        and  r["_field"] == "usage_idle" 
        and r["cpu"] == "cpu-total"
    })

// or this
var myMatcher = function(r) {
        r["_measurement"] == "cpu" 
        and  r["_field"] == "usage_idle" 
        and r["cpu"] == "cpu-total"
}
from()
    .filter(f: myMatcher)

// or even this
var baseMatcher = function(r) {
        r["_measurement"] == "cpu" 
        and  r["_field"] == "usage_idle" 
        and r["cpu"] == "cpu-total"
}
from()
    .filter(f: function(r) {
        r["some_other_tag] == "foo"
        and baseMatcher(r)
    })
```

That last example might even apply to our conversation about macros.

Having those functions without named arguments is a bit inconsistent with the language design. Although I feel we could support both, with the design requirement that any functions built into the language MUST have named arguments. While user defined functions in IFQL can have named or positional arguments. Or maybe just positional?

**Comment by nathanielc** [comment]
I hadn't really considered the last example of calling a function from a function, though it makes sense. What we were thinking for the macros is the name of the arg is the keyword name needed to call the function. So your example would look like this:

```javascript
var baseMatcher = function(record) {
        record["_measurement"] == "cpu" 
        and  record["_field"] == "usage_idle" 
        and record["cpu"] == "cpu-total"
}
from()
    .filter(f: function(r) {
        r["some_other_tag] == "foo"
        and baseMatcher(record:r) // call baseMatcher using keyword syntax
    })
```

As for the syntax the `=>` is from javascript, it is called the Arrow function and has to connotation that the function is unbounded, i.e. its not a method of an object but rather a pure anonymous function. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

I personally like the more verbose `function(r) { ... }` syntax as it more familiar but I don't have  a strong opinion, perhaps some javascript devs can chime in here on the difference between `function(r)` and `=>`? @cryptoquick @121watts 

What follows is an example mixing both functions that operate on tables (i.e. macros) and functions that operate on records. The example is trying to explore if they work well and are self consistent.

```
var mf = function(r, measurement, field) {
     r["_measurement"] == measurement and
     r["_field"] == field
}

function myFrom(db, measurement, field) {
    from(db:db)
    .filter(f: function(r) {
        mf(r:r, measurement:measurement, field:field)
    })
}

// Normalize data by renaming host_tag to "host"
function normalize(table, host_tag) {
    table.rename(old: host_tag, new:"host")
}

myFrom(db:"telegraf", measurement:"cpu", field:"usage_idle")
    // by calling `normalize` as a chain method the first keyword arg is the value of the object being chained.
    .normalize(host_tag:"server")
```

Mixing these brought up a few questions:

* What is the different between `var ident = function ...` and `function ident() ...`? Can we just pick one? If so which?
* If we allow locally defined functions to be called like built in functions how can we safely add builtin functions in the future? Should builtins be scoped to some namespace? Should local functions be scoped to a namespace?

**Comment by cryptoquick** [comment]
I prefer arrow functions. With the `function () { ... }` syntax, you also need to return to get anything. I think that's undesirable in all cases, but I could be wrong about that. With arrow functions, you get the innate understanding of an implicit return.

**Comment by pauldix** [comment]
Ok, I'd prefer the more modern `=>` syntax. Just wanted to make sure things looked familiar to JS devs.

For the function definition, I'd think just `fuction() { ... }` would be preferred? Anyone have arguments for one over the other?

For the scoping problem, would it be solved by a few things:

1.  locally defined functions can't be called as top level functions (like `from` or `join`)
2.  locally defined functions can't be chained?

If those criteria are true then I think we'd be ok, but I'm not sure they are. What would a namespacing thing look like? We definitely want the flexibility to introduce new functions without breaking people's existing code.

**Comment by nathanielc** [comment]
OK, so rewriting the above example with the current consensus.

```javascript
var mf = (r, measurement, field) => 
     r["_measurement"] == measurement and
     r["_field"] == field


function myFrom(db, measurement, field) {
    from(db:db)
    .filter(f: r => 
        mf(r:r, measurement:measurement, field:field)
    )
}

// Normalize data by renaming host_tag to "host"
function normalize(table, host_tag) {
    table.rename(old: host_tag, new:"host")
}

myFrom(db:"telegraf", measurement:"cpu", field:"usage_idle")
    // by calling `normalize` as a chain method the first keyword arg is the value of the object being chained.
    .normalize(host_tag:"server")
```

Now for this issue:

> We definitely want the flexibility to introduce new functions without breaking people's existing code.

I have a few ideas.

One option that came up before was to use a special character to indicate the call to a function that was not builtin.

```javascript
function myFrom(db, measurement, field) {
    from(db:db)
    .filter(f: r =>  r["_measurement"] == measurement and r["_field"] == field)
}

// Normalize data by renaming host_tag to "host"
function normalize(table, host_tag) {
    table.rename(old: host_tag, new:"host")
}

#myFrom(db:"telegraf", measurement:"cpu", field:"usage_idle")
    // by calling `normalize` as a chain method the first keyword arg is the value of the object being chained.
    .#normalize(host_tag:"server")
```

This way there is a clear separation between builtin functions and locally defined functions. But its a little awkward to use.

Alternatively maybe we could pose the problem as a scoping issue instead of builtin vs not.

Maybe all locally define functions are placed in the `local` namespace and builtins are in the toplevel namespace. Then later when we introduce imports, functions from imports are part of the import name namespace. This way its consistent across lots of concepts.

```javascript
import "stats" // import the stats package, which includes the "variance" function

function myFrom(db, measurement, field) {
    from(db:db)
    .filter(f: r =>  r["_measurement"] == measurement and r["_field"] == field)
}

// Normalize data by renaming host_tag to "host"
function normalize(table, host_tag) {
    table.rename(old: host_tag, new:"host")
}

local.myFrom(db:"telegraf", measurement:"cpu", field:"usage_idle")
    .range(start:1-h)
    .local.normalize(host_tag:"server")
    .stats.variance()
```

The only inconsistency here is that vars from the `stats` package will be referenced like `stats.myvar` and local vars are in the toplevel namespace. Not sure what to do about that. Ideas?

Another option is to implement some kind of two layer scoping, where lookups first search the local namespace, then search the builtin namespace. This way new additions to the builtin (toplevel) scope can never change existing behavior, but it may be necessary to rename some local functions if a new toplevel function is introduced and you want to use it. This solution leaves the syntax smaller but adds complexity in the form of a layer of indirection when determining which function/var is being used. 

Thoughts?

**Comment by pauldix** [comment]
Two layer scoping is way superior IMHO. Reading your writeup I realize that we have the problem of introducing new functions even without the function stuff because of variable names. Right now, if someone has a variable name called `interpolate` for instance and we later add that as a function, they'll have a problem. The two layer scoping fixes that.

As to the other thing where they'd need to rename local functions or variables, that's fine. They're already updating their script to reference the new function so a change isn't that big of a deal.

I think the two-layer scoping is pretty easy to understand and a far more elegant solution. So big +1 to that one.

**Comment by nathanielc** [comment]
Closing in favor of #167

**Pull request closed without merging**
